name: flutter_naver_map_pure_example
description: "the pure example of flutter_naver_map"
publish_to: 'none'

version: 1.2.1+5

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_naver_map: ^1.2.1
  geolocator: ^11.0.0
  sensors_plus: ^4.0.2
  rxdart: ^0.27.7
  lat_compass: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
