name: flutter_naver_map_pure_example
description: "the pure example of flutter_naver_map"
publish_to: 'none'

version: 1.2.1+5

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_naver_map:
    git:
      url: https://github.com/note11g/flutter_naver_map.git
      ref: dev-1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
